### ISSUE TITLE
Just running through a few issues

### ISSUE THREAD

**Issue by jonathan6620** [fetchai/colearn#83]
1. I had some installation problems - do we have a docker version of this?
2. tox is suggested for the tests but is not included in the requirements or Pipfile. 
3. For the website docs, would be hand to have the "pull this repo" link at the start of the instructions to save a bit of searching.

**Comment by evsmithx** [comment]
The installation is now contained inside the setup.py, tox is included, and the package is on pypi so I think we can close this issue.
